sudo: false

language: php

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
      env: ANALYZE=true
    - php: 7.2
    - php: hhvm
    - php: nightly
  allow_failures:
    - php: hhvm
    - php: nightly

install:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --dev

before_script:
  - if [[ $ANALYZE == 'true' ]]; then travis_retry composer require php-coveralls/php-coveralls:^1.0 ; fi;

script:
  - if [[ $ANALYZE == 'true' ]]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml ; fi;
  - if [[ $ANALYZE != 'true' ]]; then vendor/bin/phpunit ; fi;
  - if [[ $ANALYZE == 'true' ]]; then vendor/bin/phpcs ; fi

after_success:
  - if [[ $ANALYZE == 'true' ]]; then php vendor/bin/coveralls -v ; fi
